export const CATEGORIES = [
  "Tout",
  "Mobilier",
  "Vaisselle & Couverts",
  "Décoration",
  "Structure & Tente",
  "Cuisine & Service",
];

export const CATEGORY_ICONS = {
  Tout: "🏪",
  Mobilier: "🪑",
  "Vaisselle & Couverts": "🍽️",
  Décoration: "🌸",
  "Structure & Tente": "⛺",
  "Cuisine & Service": "🍳",
};

export const PRODUCTS = [
  // ── MOBILIER ──
  {
    id: 101,
    name: "Chaise plastique blanche",
    category: "Mobilier",
    emoji: "🪑",
    desc: "Chaise empilable solide, idéale pour cérémonies et réceptions en plein air.",
    pricePerDay: 150,
    unit: "par chaise / jour",
    minQty: 10,
    maxQty: 500,
    stock: 400,
    badge: "Populaire",
    badgeColor: "#FFD700",
    features: ["Empilable", "Légère", "Intérieur & Extérieur"],
  },
  {
    id: 102,
    name: "Chaise Chiavari dorée",
    category: "Mobilier",
    emoji: "👑",
    desc: "Chaise élégante dorée, parfaite pour les mariages et cérémonies haut de gamme.",
    pricePerDay: 500,
    unit: "par chaise / jour",
    minQty: 10,
    maxQty: 200,
    stock: 150,
    badge: "Premium",
    badgeColor: "#0047AB",
    features: ["Design luxe", "Mariage & Gala", "Très résistante"],
  },
  {
    id: 103,
    name: "Table ronde 8 personnes",
    category: "Mobilier",
    emoji: "⭕",
    desc: "Table ronde de 160cm de diamètre, convient pour 8 à 10 personnes.",
    pricePerDay: 2000,
    unit: "par table / jour",
    minQty: 1,
    maxQty: 80,
    stock: 60,
    badge: null,
    badgeColor: null,
    features: ["Ø 160cm", "8-10 pers.", "Pliable"],
  },
  {
    id: 104,
    name: "Table rectangulaire 6 personnes",
    category: "Mobilier",
    emoji: "▬",
    desc: "Table rectangulaire solide pour buffet ou repas. Légère et facile à transporter.",
    pricePerDay: 1500,
    unit: "par table / jour",
    minQty: 1,
    maxQty: 100,
    stock: 80,
    badge: null,
    badgeColor: null,
    features: ["180×80cm", "6 pers.", "Pliable"],
  },
  {
    id: 105,
    name: "Table haute cocktail",
    category: "Mobilier",
    emoji: "🍸",
    desc: "Table haute pour cocktail et vin d'honneur, apporte une touche moderne.",
    pricePerDay: 1800,
    unit: "par table / jour",
    minQty: 2,
    maxQty: 40,
    stock: 30,
    badge: "Tendance",
    badgeColor: "#008000",
    features: ["Hauteur bar", "Moderne", "Cocktail & Vin d'honneur"],
  },
  {
    id: 106,
    name: "Mange-debout avec housse",
    category: "Mobilier",
    emoji: "🎪",
    desc: "Mange-debout avec housse blanche ou colorée selon disponibilité.",
    pricePerDay: 2500,
    unit: "par unité / jour",
    minQty: 2,
    maxQty: 20,
    stock: 20,
    badge: null,
    badgeColor: null,
    features: ["Housse incluse", "Élégant", "Blanc ou coloré"],
  },

  // ── VAISSELLE & COUVERTS ──
  {
    id: 201,
    name: "Assiette plate blanche",
    category: "Vaisselle & Couverts",
    emoji: "🍽️",
    desc: "Assiette en porcelaine blanche, idéale pour tous types de repas.",
    pricePerDay: 75,
    unit: "par assiette / jour",
    minQty: 20,
    maxQty: 1000,
    stock: 800,
    badge: "Populaire",
    badgeColor: "#FFD700",
    features: ["Porcelaine", "Lave-vaisselle OK", "Blanc uni"],
  },
  {
    id: 202,
    name: "Assiette creuse",
    category: "Vaisselle & Couverts",
    emoji: "🥣",
    desc: "Assiette creuse en porcelaine pour soupes, plats en sauce et salades.",
    pricePerDay: 75,
    unit: "par assiette / jour",
    minQty: 20,
    maxQty: 800,
    stock: 600,
    badge: null,
    badgeColor: null,
    features: ["Porcelaine", "Profondeur 4cm", "Blanc uni"],
  },
  {
    id: 203,
    name: "Verre à eau",
    category: "Vaisselle & Couverts",
    emoji: "🥛",
    desc: "Verre transparent classique, solide et élégant pour eau et jus.",
    pricePerDay: 50,
    unit: "par verre / jour",
    minQty: 20,
    maxQty: 1500,
    stock: 1200,
    badge: null,
    badgeColor: null,
    features: ["Verre trempé", "25cl", "Transparent"],
  },
  {
    id: 204,
    name: "Flûte à champagne",
    category: "Vaisselle & Couverts",
    emoji: "🥂",
    desc: "Flûte élégante pour champagne, mousseux et cocktails festifs.",
    pricePerDay: 100,
    unit: "par flûte / jour",
    minQty: 10,
    maxQty: 500,
    stock: 400,
    badge: "Fêtes",
    badgeColor: "#FFD700",
    features: ["Verre fin", "18cl", "Festif"],
  },
  {
    id: 205,
    name: "Couvert inox complet",
    category: "Vaisselle & Couverts",
    emoji: "🍴",
    desc: "Set couteau + fourchette + cuillère en inox brossé, qualité professionnelle.",
    pricePerDay: 100,
    unit: "par set / jour",
    minQty: 20,
    maxQty: 1000,
    stock: 900,
    badge: null,
    badgeColor: null,
    features: ["Inox 18/10", "3 pièces", "Professionnel"],
  },
  {
    id: 206,
    name: "Plat de service ovale",
    category: "Vaisselle & Couverts",
    emoji: "🫕",
    desc: "Grand plat ovale en porcelaine pour présentation et service à table.",
    pricePerDay: 300,
    unit: "par plat / jour",
    minQty: 5,
    maxQty: 100,
    stock: 80,
    badge: null,
    badgeColor: null,
    features: ["40×28cm", "Porcelaine", "Service traiteur"],
  },

  // ── DÉCORATION ──
  {
    id: 301,
    name: "Nappe blanche ronde",
    category: "Décoration",
    emoji: "⬜",
    desc: "Nappe en tissu blanc pour table ronde, tombée élégante jusqu'au sol.",
    pricePerDay: 500,
    unit: "par nappe / jour",
    minQty: 5,
    maxQty: 200,
    stock: 150,
    badge: null,
    badgeColor: null,
    features: ["Tissu polyester", "Ø 230cm", "Repassée"],
  },
  {
    id: 302,
    name: "Chemin de table doré",
    category: "Décoration",
    emoji: "✨",
    desc: "Chemin de table en satin doré, parfait pour mariages et cérémonies.",
    pricePerDay: 400,
    unit: "par chemin / jour",
    minQty: 5,
    maxQty: 150,
    stock: 100,
    badge: "Mariage",
    badgeColor: "#FFD700",
    features: ["Satin doré", "30×270cm", "Luxueux"],
  },
  {
    id: 303,
    name: "Housse de chaise blanche",
    category: "Décoration",
    emoji: "🎀",
    desc: "Housse en lycra blanc pour chaises plastiques, transforme la salle instantanément.",
    pricePerDay: 200,
    unit: "par housse / jour",
    minQty: 10,
    maxQty: 400,
    stock: 350,
    badge: "Populaire",
    badgeColor: "#FFD700",
    features: ["Lycra stretch", "Universel", "Blanc ou coloré"],
  },
  {
    id: 304,
    name: "Nœud de chaise satin",
    category: "Décoration",
    emoji: "🎗️",
    desc: "Nœud décoratif en satin pour chaises, disponible en plusieurs couleurs.",
    pricePerDay: 100,
    unit: "par nœud / jour",
    minQty: 10,
    maxQty: 400,
    stock: 300,
    badge: null,
    badgeColor: null,
    features: ["Satin", "Multi-couleurs", "Facile à poser"],
  },
  {
    id: 305,
    name: "Photobooth cadre doré",
    category: "Décoration",
    emoji: "📸",
    desc: "Cadre photobooth doré 2m×1.5m avec accessoires pour animer vos fêtes.",
    pricePerDay: 8000,
    unit: "par cadre / jour",
    minQty: 1,
    maxQty: 3,
    stock: 3,
    badge: "Tendance",
    badgeColor: "#008000",
    features: ["2m×1.5m", "Accessoires inclus", "Installation incluse"],
  },

  // ── STRUCTURE & TENTE ──
  {
    id: 401,
    name: "Bâche blanche 5×10m",
    category: "Structure & Tente",
    emoji: "⛺",
    desc: "Bâche imperméable blanche pour protéger vos invités du soleil et de la pluie.",
    pricePerDay: 15000,
    unit: "par bâche / jour",
    minQty: 1,
    maxQty: 10,
    stock: 8,
    badge: "Populaire",
    badgeColor: "#FFD700",
    features: ["5×10m", "Imperméable", "Pose incluse"],
  },
  {
    id: 402,
    name: "Bâche transparente 5×10m",
    category: "Structure & Tente",
    emoji: "🌂",
    desc: "Bâche transparente moderne, idéale pour les événements en plein air élégants.",
    pricePerDay: 20000,
    unit: "par bâche / jour",
    minQty: 1,
    maxQty: 5,
    stock: 4,
    badge: "Premium",
    badgeColor: "#0047AB",
    features: ["5×10m", "Transparente", "Pose incluse"],
  },
  {
    id: 403,
    name: "Podium / Scène 4×6m",
    category: "Structure & Tente",
    emoji: "🎭",
    desc: "Podium modulable pour discours, remise de prix, spectacle et animation.",
    pricePerDay: 25000,
    unit: "par podium / jour",
    minQty: 1,
    maxQty: 2,
    stock: 2,
    badge: null,
    badgeColor: null,
    features: ["4×6m", "Hauteur 60cm", "Modulable"],
  },

  // ── CUISINE & SERVICE ──
  {
    id: 501,
    name: "Chafing dish inox",
    category: "Cuisine & Service",
    emoji: "🍲",
    desc: "Chafing dish professionnel pour maintenir vos plats au chaud pendant le service.",
    pricePerDay: 3000,
    unit: "par unité / jour",
    minQty: 2,
    maxQty: 20,
    stock: 15,
    badge: null,
    badgeColor: null,
    features: ["Inox 18/10", "9L", "Combustible inclus"],
  },
  {
    id: 502,
    name: "Fontaine à eau fraîche",
    category: "Cuisine & Service",
    emoji: "💧",
    desc: "Fontaine réfrigérée pour eau fraîche en libre-service, capacité 20L.",
    pricePerDay: 5000,
    unit: "par fontaine / jour",
    minQty: 1,
    maxQty: 5,
    stock: 5,
    badge: null,
    badgeColor: null,
    features: ["20L", "Réfrigérée", "Libre-service"],
  },
  {
    id: 503,
    name: "Glacière 100L",
    category: "Cuisine & Service",
    emoji: "🧊",
    desc: "Grande glacière isotherme pour garder vos boissons fraîches toute la journée.",
    pricePerDay: 4000,
    unit: "par glacière / jour",
    minQty: 1,
    maxQty: 8,
    stock: 8,
    badge: "Essentiel",
    badgeColor: "#008000",
    features: ["100L", "48h maintien froid", "Avec roulettes"],
  },
];

export const BRANDS = [...new Set(PRODUCTS.map((p) => p.category))];

export const PRICE_RANGES = [
  { label: "Moins de 500 FCFA", max: 500 },
  { label: "500 – 2 000 FCFA", max: 2000 },
  { label: "2 000 – 10 000 FCFA", max: 10000 },
  { label: "Plus de 10 000 FCFA", max: Infinity },
];
