export const SERVICES = [
  {
    id: "traiteur",
    emoji: "🍽️",
    title: "Traiteur & Restauration",
    tagline: "Des saveurs qui marquent les esprits",
    color: "#FFD700",
    colorDark: "#B89800",
    colorBg: "rgba(255,215,0,0.08)",
    colorBorder: "rgba(255,215,0,0.25)",
    desc: "Notre équipe de cuisiniers professionnels prend en charge l'intégralité de votre restauration. Menu local ou international, buffet ou service à table — nous nous adaptons à votre événement et à votre budget.",
    includes: [
      "Consultation menu gratuite",
      "Cuisine sur place ou en livraison",
      "Service à table inclus",
      "Vaisselle et couverts disponibles",
      "Menus végétariens disponibles",
      "Devis en moins de 24h",
    ],
    packs: [
      {
        name: "Essentiel",
        price: "À partir de 2 500 FCFA / pers.",
        desc: "Menu simple, idéal pour cérémonies familiales",
      },
      {
        name: "Confort",
        price: "À partir de 5 000 FCFA / pers.",
        desc: "Menu 3 services, entrée + plat + dessert",
      },
      {
        name: "Premium",
        price: "Sur devis",
        desc: "Menu gastronomique, service blanc gants",
      },
    ],
    gallery: ["🥘", "🍖", "🥗", "🍰"],
    occasions: [
      "Mariage",
      "Baptême",
      "Anniversaire",
      "Entreprise",
      "Conférence",
    ],
  },
  {
    id: "decoration",
    emoji: "🌸",
    title: "Décoration & Mise en scène",
    tagline: "Transformez chaque espace en décor de rêve",
    color: "#008000",
    colorDark: "#005500",
    colorBg: "rgba(0,128,0,0.08)",
    colorBorder: "rgba(0,128,0,0.25)",
    desc: "Notre équipe de décorateurs crée une ambiance unique selon votre thème et vos couleurs. Fleurs, lumières, arches, centres de table — chaque détail est pensé pour que votre événement soit inoubliable.",
    includes: [
      "Consultation décoration gratuite",
      "Conception du plan de salle",
      "Installation & démontage inclus",
      "Fleurs fraîches ou artificielles",
      "Éclairage LED et guirlandes",
      "Photos de référence fournies",
    ],
    packs: [
      {
        name: "Essentiel",
        price: "À partir de 50 000 FCFA",
        desc: "Décoration de salle simple, 1 couleur dominante",
      },
      {
        name: "Élégance",
        price: "À partir de 120 000 FCFA",
        desc: "Thème complet, fleurs, lumières, arche",
      },
      {
        name: "Luxe",
        price: "Sur devis",
        desc: "Création sur mesure, décor haute couture",
      },
    ],
    gallery: ["💐", "✨", "🕯️", "🎊"],
    occasions: [
      "Mariage",
      "Fiançailles",
      "Baptême",
      "Anniversaire",
      "Saint-Valentin",
    ],
  },
  {
    id: "animation",
    emoji: "🎤",
    title: "Animation & DJ",
    tagline: "L'ambiance qui fait danser toute la nuit",
    color: "#0047AB",
    colorDark: "#003A8C",
    colorBg: "rgba(0,71,171,0.08)",
    colorBorder: "rgba(0,71,171,0.25)",
    desc: "DJs professionnels, maîtres de cérémonie, animateurs jeunesse — nous assurons l'animation complète de votre événement du début à la fin. Playlist sur mesure, jeux, quiz, ambiance garantie.",
    includes: [
      "DJ professionnel certifié",
      "Playlist selon vos goûts",
      "Maître de cérémonie disponible",
      "Animation enfants en option",
      "Jeux et concours inclus",
      "Micro et podium fournis",
    ],
    packs: [
      {
        name: "DJ 4h",
        price: "À partir de 40 000 FCFA",
        desc: "DJ seul, 4 heures d'animation",
      },
      {
        name: "DJ + MC",
        price: "À partir de 75 000 FCFA",
        desc: "DJ + Maître de cérémonie, soirée complète",
      },
      {
        name: "Full Show",
        price: "Sur devis",
        desc: "Animation complète, show, effets spéciaux",
      },
    ],
    gallery: ["🎵", "💃", "🎶", "🎊"],
    occasions: ["Mariage", "Anniversaire", "Soirée entreprise", "Bal", "Gala"],
  },
  {
    id: "sonorisation",
    emoji: "🔊",
    title: "Sonorisation & Éclairage",
    tagline: "Le son et la lumière qui subliment votre événement",
    color: "#FFD700",
    colorDark: "#B89800",
    colorBg: "rgba(255,215,0,0.08)",
    colorBorder: "rgba(255,215,0,0.25)",
    desc: "Équipement audio et lumière professionnel pour toutes les tailles d'événements. Enceintes, micros, mixage, jeux de lumières LED — nous installons, réglons et assurons la technique pendant toute la durée.",
    includes: [
      "Enceintes professionnelles",
      "Micros filaires et HF",
      "Table de mixage",
      "Jeux de lumières LED",
      "Technicien son sur place",
      "Installation & démontage",
    ],
    packs: [
      {
        name: "Petite salle",
        price: "À partir de 30 000 FCFA",
        desc: "Jusqu'à 100 personnes, 2 enceintes",
      },
      {
        name: "Grande salle",
        price: "À partir de 60 000 FCFA",
        desc: "100-300 personnes, système complet",
      },
      {
        name: "Plein air",
        price: "Sur devis",
        desc: "+300 personnes, sono outdoor puissante",
      },
    ],
    gallery: ["🎙️", "💡", "🔆", "🎛️"],
    occasions: ["Conférence", "Mariage", "Concert", "Soirée gala", "Cérémonie"],
  },
];

export const OCCASIONS = [
  "Mariage",
  "Baptême",
  "Anniversaire",
  "Entreprise",
  "Conférence",
  "Gala",
  "Autre",
];

export const BUDGETS = [
  "Moins de 100 000 FCFA",
  "100 000 – 300 000 FCFA",
  "300 000 – 500 000 FCFA",
  "500 000 – 1 000 000 FCFA",
  "Plus de 1 000 000 FCFA",
  "Je ne sais pas encore",
];
