export const PRODUCTS = [
  // ── BIÈRES ──
  {
    id: 1,
    name: "Castel Beer",
    category: "Bières",
    emoji: "🍺",
    desc: "La bière blonde légère la plus populaire du Bénin. Idéale pour vos fêtes.",
    price: 500,
    unit: "bouteille 65cl",
    volume: true,
    formats: ["33cl", "65cl"],
    stock: 120,
    badge: "Populaire",
    badgeColor: "#FFD700",
    promo: null,
    brand: "Castel",
    alc: "5.5%",
  },
  {
    id: 2,
    name: "La Béninoise",
    category: "Bières",
    emoji: "🍻",
    desc: "La bière locale emblématique. Un goût authentique apprécié de tous.",
    price: 450,
    unit: "bouteille 65cl",
    volume: true,
    formats: ["65cl"],
    stock: 80,
    badge: "Local",
    badgeColor: "#008000",
    promo: null,
    brand: "La Béninoise",
    alc: "5.8%",
  },
  {
    id: 3,
    name: "Heineken",
    category: "Bières",
    emoji: "🍺",
    desc: "La bière internationale premium, fraîche et légèrement amère.",
    price: 700,
    unit: "bouteille 33cl",
    volume: true,
    formats: ["25cl", "33cl"],
    stock: 50,
    badge: "Premium",
    badgeColor: "#0047AB",
    promo: null,
    brand: "Heineken",
    alc: "5%",
  },
  {
    id: 4,
    name: "Guinness",
    category: "Bières",
    emoji: "🥃",
    desc: "La stout irlandaise, brune et crémeuse. Pour les amateurs de caractère.",
    price: 800,
    unit: "bouteille 33cl",
    volume: true,
    formats: ["33cl"],
    stock: 30,
    badge: null,
    badgeColor: null,
    promo: 10,
    brand: "Guinness",
    alc: "7.5%",
  },
  {
    id: 5,
    name: "Desperados",
    category: "Bières",
    emoji: "🍺",
    desc: "Bière aromatisée à la tequila. Festive et originale.",
    price: 900,
    unit: "bouteille 33cl",
    volume: true,
    formats: ["33cl"],
    stock: 20,
    badge: "Festif",
    badgeColor: "#FFD700",
    promo: null,
    brand: "Desperados",
    alc: "5.9%",
  },

  // ── JUS NATURELS ──
  {
    id: 6,
    name: "Jus de Bissap",
    category: "Jus naturels",
    emoji: "🫐",
    desc: "Hibiscus rouge, sucré et légèrement acidulé. Fait maison chaque matin.",
    price: 300,
    unit: "bouteille 50cl",
    volume: true,
    formats: ["25cl", "50cl", "1L"],
    stock: 60,
    badge: "Naturel",
    badgeColor: "#008000",
    promo: null,
    brand: "Artisanal",
    alc: "0%",
  },
  {
    id: 7,
    name: "Jus de Gingembre",
    category: "Jus naturels",
    emoji: "🫚",
    desc: "Gingembre frais pressé, tonique et énergisant. Un classique béninois.",
    price: 350,
    unit: "bouteille 50cl",
    volume: true,
    formats: ["50cl", "1L"],
    stock: 45,
    badge: "Naturel",
    badgeColor: "#008000",
    promo: null,
    brand: "Artisanal",
    alc: "0%",
  },
  {
    id: 8,
    name: "Jus de Tamarin",
    category: "Jus naturels",
    emoji: "🍶",
    desc: "Tamarin acidulé et rafraîchissant. Boisson traditionnelle incontournable.",
    price: 300,
    unit: "bouteille 50cl",
    volume: true,
    formats: ["50cl"],
    stock: 35,
    badge: "Traditionnel",
    badgeColor: "#0047AB",
    promo: 5,
    brand: "Artisanal",
    alc: "0%",
  },
  {
    id: 9,
    name: "Jus de Mangue Frais",
    category: "Jus naturels",
    emoji: "🥭",
    desc: "Mangue locale fraîchement pressée. Disponible en saison.",
    price: 400,
    unit: "bouteille 50cl",
    volume: true,
    formats: ["50cl", "1L"],
    stock: 0,
    badge: "Saisonnier",
    badgeColor: "#FFD700",
    promo: null,
    brand: "Artisanal",
    alc: "0%",
  },

  // ── SODAS ──
  {
    id: 10,
    name: "Coca-Cola",
    category: "Sodas",
    emoji: "🥤",
    desc: "Le classique intemporel. Idéal pour tous les événements.",
    price: 300,
    unit: "bouteille 50cl",
    volume: true,
    formats: ["33cl", "50cl", "1L", "1.5L"],
    stock: 200,
    badge: null,
    badgeColor: null,
    promo: null,
    brand: "Coca-Cola",
    alc: "0%",
  },
  {
    id: 11,
    name: "Fanta Orange",
    category: "Sodas",
    emoji: "🍊",
    desc: "Soda orange pétillant et sucré, adoré des enfants.",
    price: 300,
    unit: "bouteille 50cl",
    volume: true,
    formats: ["33cl", "50cl"],
    stock: 150,
    badge: null,
    badgeColor: null,
    promo: null,
    brand: "Coca-Cola",
    alc: "0%",
  },
  {
    id: 12,
    name: "Sprite",
    category: "Sodas",
    emoji: "🍋",
    desc: "Citron vert pétillant, désaltérant et sans caféine.",
    price: 300,
    unit: "bouteille 50cl",
    volume: true,
    formats: ["33cl", "50cl"],
    stock: 130,
    badge: null,
    badgeColor: null,
    promo: 5,
    brand: "Coca-Cola",
    alc: "0%",
  },
  {
    id: 13,
    name: "Malta Guinness",
    category: "Sodas",
    emoji: "🧃",
    desc: "Boisson maltée non alcoolisée, riche en vitamines et minéraux.",
    price: 350,
    unit: "bouteille 33cl",
    volume: true,
    formats: ["33cl"],
    stock: 90,
    badge: "Énergisant",
    badgeColor: "#008000",
    promo: null,
    brand: "Guinness",
    alc: "0%",
  },

  // ── EAUX ──
  {
    id: 14,
    name: "Eau Minérale Possotomé",
    category: "Eaux",
    emoji: "💧",
    desc: "Eau minérale naturelle béninoise, pure et équilibrée en sels minéraux.",
    price: 300,
    unit: "bouteille 1.5L",
    volume: true,
    formats: ["50cl", "1L", "1.5L"],
    stock: 300,
    badge: "Local",
    badgeColor: "#008000",
    promo: null,
    brand: "Possotomé",
    alc: "0%",
  },
  {
    id: 15,
    name: "Eau Pétillante",
    category: "Eaux",
    emoji: "✨",
    desc: "Eau gazeuse rafraîchissante. Parfaite pour accompagner vos repas.",
    price: 400,
    unit: "bouteille 75cl",
    volume: true,
    formats: ["33cl", "75cl"],
    stock: 80,
    badge: null,
    badgeColor: null,
    promo: null,
    brand: "Importée",
    alc: "0%",
  },

  // ── VINS & SPIRITUEUX ──
  {
    id: 16,
    name: "Vin Rouge Cabernet",
    category: "Vins & Spiritueux",
    emoji: "🍷",
    desc: "Vin rouge sec et fruité, idéal pour vos dîners et cérémonies.",
    price: 4500,
    unit: "bouteille 75cl",
    volume: true,
    formats: ["75cl"],
    stock: 25,
    badge: "Premium",
    badgeColor: "#0047AB",
    promo: null,
    brand: "Importé",
    alc: "13%",
  },
  {
    id: 17,
    name: "Champagne Mousseux",
    category: "Vins & Spiritueux",
    emoji: "🥂",
    desc: "Pétillant festif pour vos toasts et célébrations. Élégant et abordable.",
    price: 6000,
    unit: "bouteille 75cl",
    volume: true,
    formats: ["75cl"],
    stock: 15,
    badge: "Fêtes",
    badgeColor: "#FFD700",
    promo: null,
    brand: "Importé",
    alc: "11%",
  },
];

export const CATEGORIES = [
  "Tout",
  "Bières",
  "Jus naturels",
  "Sodas",
  "Eaux",
  "Vins & Spiritueux",
];

export const BRANDS = [...new Set(PRODUCTS.map((p) => p.brand))];

export const CATEGORY_ICONS = {
  Tout: "🛒",
  Bières: "🍺",
  "Jus naturels": "🥤",
  Sodas: "🧃",
  Eaux: "💧",
  "Vins & Spiritueux": "🍷",
};
